let STORAGE_KEY = 'gradetrack-data-v1';
const defaultData = { profile: { name: 'Mat', course: 'Student', studentId: '' }, subjects: [], grades: [], files: [] };
const USERS_KEY = 'gradetrack-users-v1';
let currentUser = localStorage.getItem('gradetrack-session');
let data = loadData();
let history = [];
let future = [];

function loadData() { try { return { ...defaultData, ...JSON.parse(localStorage.getItem(STORAGE_KEY)) }; } catch { return structuredClone(defaultData); } }
function saveData() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function snapshot() { return JSON.stringify(data); }
function restore(value) { data = JSON.parse(value); saveData(); render(); }
function commit(message, action) { history.push({ before: snapshot(), message }); future = []; action(); saveData(); render(); toast(message); }
function undo() { const item = history.pop(); if (!item) return; future.push({ before: snapshot(), after: item.before, message: item.message }); restore(item.before); toast('Undid ' + item.message.toLowerCase()); }
function redo() { const item = future.pop(); if (!item) return; history.push({ before: snapshot(), message: item.message }); restore(item.before); toast('Redid ' + item.message.toLowerCase()); }
function toast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 2200); }
async function passwordHash(password) { const bytes = new TextEncoder().encode(password); const digest = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join(''); }
function users() { try { return JSON.parse(localStorage.getItem(USERS_KEY)) || {}; } catch { return {}; } }
function setUser(username) { currentUser = username; STORAGE_KEY = `gradetrack-data-${username}`; data = loadData(); history = []; future = []; document.getElementById('auth-screen').classList.add('hidden'); document.querySelector('.app-shell').classList.remove('hidden'); render(); }
function showAuthError(message) { document.getElementById('auth-error').textContent = message; }
function setAuthMode(registering) { document.getElementById('register-fields').classList.toggle('hidden', !registering); document.getElementById('login-copy').classList.toggle('hidden', registering); document.getElementById('register-copy').classList.toggle('hidden', !registering); document.getElementById('auth-submit').textContent = registering ? 'Create account' : 'Sign in'; document.getElementById('auth-switch').innerHTML = registering ? 'Already have an account? <strong>Sign in here</strong>' : 'Need an account? <strong>Register here</strong>'; document.getElementById('auth-form').dataset.mode = registering ? 'register' : 'login'; showAuthError(''); }
function esc(value) { return String(value).replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[ch])); }
function averageFor(subject) { const grades = data.grades.filter(g => g.subject === subject); if (!grades.length) return 0; const subjectConfig = data.subjects.find(s => s.name === subject); const weights = (subjectConfig?.weights || '').split(',').map(part => { const match = part.trim().match(/^(.+?)\s+(\d+(?:\.\d+)?)$/); return match ? { category: match[1].trim().toLowerCase(), weight: Number(match[2]) } : null; }).filter(Boolean); if (!weights.length) return grades.reduce((sum, g) => sum + Number(g.score) / Number(g.total) * 100, 0) / grades.length; const totalWeight = weights.reduce((sum, item) => sum + item.weight, 0); return weights.reduce((sum, item) => { const categoryGrades = grades.filter(g => (g.category || 'Other').toLowerCase() === item.category); if (!categoryGrades.length) return sum; const categoryAverage = categoryGrades.reduce((inner, g) => inner + Number(g.score) / Number(g.total) * 100, 0) / categoryGrades.length; return sum + categoryAverage * item.weight / totalWeight; }, 0) || grades.reduce((sum, g) => sum + Number(g.score) / Number(g.total) * 100, 0) / grades.length; }
function overallAverage() { if (!data.grades.length) return 0; return data.grades.reduce((sum, g) => sum + Number(g.score) / Number(g.total) * 100, 0) / data.grades.length; }
function formatDate(value) { return new Date(value + 'T00:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); }
function initials(name) { return name.split(' ').filter(Boolean).map(word => word[0]).join('').slice(0, 2).toUpperCase() || 'MP'; }
function render() { renderProfile(); renderStats(); renderSubjects(); renderGrades(); renderRecent(); renderChart(); renderInsights(); renderFiles(); updateButtons(); }
function renderProfile() { const profile = data.profile; document.getElementById('sidebar-avatar').textContent = initials(profile.name); document.getElementById('sidebar-name').textContent = profile.name || 'My profile'; document.getElementById('sidebar-course').textContent = profile.course || 'Student'; document.getElementById('page-title').textContent = `Good morning, ${profile.name || 'there'}!`; document.getElementById('today-label').textContent = new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }); }
function renderStats() { const avg = overallAverage(); document.getElementById('average-stat').textContent = avg ? `${avg.toFixed(1)}%` : '0.0%'; document.getElementById('average-note').textContent = avg ? (avg >= 90 ? 'Excellent consistency' : avg >= 75 ? 'Solid progress so far' : 'Room to improve') : 'Add grades to see your average'; document.getElementById('grade-count-stat').textContent = data.grades.length; document.getElementById('grade-count-note').textContent = data.grades.length === 1 ? 'One result logged' : 'Across all subjects'; document.getElementById('subject-count-stat').textContent = data.subjects.length; document.getElementById('subject-count-note').textContent = data.subjects.length ? 'Classes in your course map' : 'Set up your classes'; const ranked = data.subjects.map(s => ({ ...s, avg: averageFor(s.name) })).filter(s => s.avg).sort((a, b) => b.avg - a.avg); document.getElementById('best-subject-stat').textContent = ranked[0]?.name || '--'; document.getElementById('best-subject-note').textContent = ranked[0] ? `${ranked[0].avg.toFixed(1)}% average` : 'Your strongest average'; }
function renderSubjects() { const list = document.getElementById('subject-list'); list.innerHTML = data.subjects.length ? data.subjects.map(s => `<div class="subject-row"><div class="subject-main"><strong>${esc(s.name)}</strong><span>${data.grades.filter(g => g.subject === s.name).length} assessments</span></div><span class="score">${averageFor(s.name) ? averageFor(s.name).toFixed(1) + '%' : '--'}</span></div>`).join('') : '<div class="empty-state compact"><strong>No subjects yet</strong><span>Add your classes to get started.</span></div>';
 const grid = document.getElementById('subjects-grid'); grid.innerHTML = data.subjects.length ? data.subjects.map(s => { const avg = averageFor(s.name); return `<article class="subject-card"><div class="subject-card-top"><h3>${esc(s.name)}</h3><button class="delete-button" data-delete-subject="${esc(s.name)}" title="Delete subject">x</button></div><div class="subject-average">${avg ? avg.toFixed(1) + '%' : '--'}</div><div class="progress-bar"><i style="width:${Math.min(avg, 100)}%"></i></div><small>${data.grades.filter(g => g.subject === s.name).length} assessments ${s.weights ? `| ${esc(s.weights)}` : ''}</small></article>` }).join('') : '<div class="empty-state"><strong>No subjects in your course map</strong><span>Add your first class to begin.</span></div>';
 document.querySelectorAll('[data-delete-subject]').forEach(button => button.addEventListener('click', () => { const name = button.dataset.deleteSubject; commit(`Deleted ${name}`, () => { data.subjects = data.subjects.filter(s => s.name !== name); data.grades = data.grades.filter(g => g.subject !== name); }); })); updateSubjectSelects(); }
function renderGrades() { const query = document.getElementById('grade-search')?.value.toLowerCase() || ''; const filter = document.getElementById('grade-filter')?.value || 'all'; const grades = data.grades.filter(g => (filter === 'all' || g.subject === filter) && `${g.activity} ${g.subject}`.toLowerCase().includes(query)).sort((a, b) => b.date.localeCompare(a.date)); const body = document.getElementById('grades-table'); body.innerHTML = grades.map(g => `<tr><td><strong>${esc(g.activity)}</strong></td><td>${esc(g.subject)}</td><td>${g.score} / ${g.total}</td><td><span class="percent-pill">${(g.score / g.total * 100).toFixed(1)}%</span></td><td>${formatDate(g.date)}</td><td><button class="delete-button" data-delete-grade="${g.id}" title="Delete grade">x</button></td></tr>`).join(''); document.getElementById('grades-empty').classList.toggle('hidden', Boolean(grades.length)); document.querySelectorAll('[data-delete-grade]').forEach(button => button.addEventListener('click', () => { const grade = data.grades.find(g => g.id === button.dataset.deleteGrade); commit(`Deleted ${grade.activity}`, () => { data.grades = data.grades.filter(g => g.id !== grade.id); }); })); }
function renderRecent() { const recent = [...data.grades].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4); document.getElementById('recent-list').innerHTML = recent.length ? recent.map(g => `<div class="activity-row"><div class="activity-main"><strong>${esc(g.activity)}</strong><span>${esc(g.subject)} | ${formatDate(g.date)}</span></div><span class="score">${(g.score / g.total * 100).toFixed(0)}%</span></div>`).join('') : '<div class="empty-state compact"><strong>No grades yet</strong><span>Start with your first assessment.</span></div>'; }
function renderChart() { const grades = [...data.grades].sort((a, b) => a.date.localeCompare(b.date)).slice(-8); const points = grades.map((g, i) => ({ x: 45 + (i * 635 / Math.max(grades.length - 1, 1)), y: 180 - ((g.score / g.total * 100) / 100 * 150) })); document.getElementById('chart-line').setAttribute('d', points.length ? points.map((p, i) => `${i ? 'L' : 'M'}${p.x} ${p.y}`).join(' ') : 'M45 180'); document.getElementById('chart-points').innerHTML = points.map(p => `<circle class="chart-point" cx="${p.x}" cy="${p.y}" r="5"/>`).join(''); document.getElementById('chart-caption').textContent = grades.length ? `${grades.length} latest result${grades.length === 1 ? '' : 's'}` : 'Your latest grades will appear here'; }
function renderInsights() { const ranked = data.subjects.map(s => ({ ...s, avg: averageFor(s.name) })).sort((a, b) => b.avg - a.avg); document.getElementById('insight-bars').innerHTML = ranked.length ? ranked.map(s => `<div><div class="bar-label"><strong>${esc(s.name)}</strong><span>${s.avg ? s.avg.toFixed(1) + '%' : 'No grades'}</span></div><div class="bar-track"><i style="width:${Math.min(s.avg, 100)}%"></i></div></div>`).join('') : '<div class="empty-state compact"><strong>No analytics yet</strong><span>Add subjects and grades to see signals.</span></div>'; const focus = [...ranked].filter(s => s.avg).sort((a, b) => a.avg - b.avg)[0]; document.getElementById('focus-subject').textContent = focus ? `${focus.avg.toFixed(1)}%` : '--'; document.getElementById('focus-title').textContent = focus ? `${focus.name} is your next opportunity.` : 'Add a subject to get a focus recommendation.'; document.getElementById('focus-copy').textContent = focus ? 'A little focused attention here can lift your overall average fastest.' : 'GradeTrack compares your subject averages so your next study block has a direction.'; }
function renderFiles() { const list = document.getElementById('files-list'); list.innerHTML = data.files.map(f => `<div class="file-row"><div class="file-icon">FILE</div><div class="file-main"><strong>${esc(f.name)}</strong><span>${esc(f.subject || 'General')} | Submitted ${formatDate(f.date)}</span></div><div class="file-actions">${f.content ? `<button class="outline-button" data-view-file="${f.id}" type="button">View</button>` : '<span class="label-hint">Preview unavailable</span>'}<button class="delete-button" data-delete-file="${f.id}" title="Remove file">x</button></div></div>`).join(''); document.getElementById('files-empty').classList.toggle('hidden', Boolean(data.files.length)); document.querySelectorAll('[data-view-file]').forEach(button => button.addEventListener('click', () => { const file = data.files.find(item => item.id === button.dataset.viewFile); if (!file?.content) return toast('This file is no longer available'); const preview = window.open('', '_blank'); if (!preview) return toast('Please allow pop-ups to view this file'); preview.document.write(`<title>${esc(file.name)}</title><iframe src="${file.content}" style="width:100%;height:100vh;border:0" title="${esc(file.name)}"></iframe>`); preview.document.close(); })); document.querySelectorAll('[data-delete-file]').forEach(button => button.addEventListener('click', () => commit('Removed file', () => { data.files = data.files.filter(f => f.id !== button.dataset.deleteFile); }))); }
function updateSubjectSelects() { const options = data.subjects.map(s => `<option value="${esc(s.name)}">${esc(s.name)}</option>`).join(''); document.getElementById('grade-subject').innerHTML = options || '<option value="">Add a subject first</option>'; const filter = document.getElementById('grade-filter'); const current = filter.value; filter.innerHTML = '<option value="all">All subjects</option>' + options; filter.value = [...filter.options].some(o => o.value === current) ? current : 'all'; }
function updateButtons() { document.getElementById('undo-button').disabled = !history.length; document.getElementById('redo-button').disabled = !future.length; }
function openDialog(id) { const dialog = document.getElementById(id); if (id === 'grade-dialog' && !data.subjects.length) { toast('Add a subject before logging a grade'); showView('subjects'); return; } if (id === 'grade-dialog') document.querySelector('#grade-form [name=date]').value = new Date().toISOString().slice(0, 10); dialog.showModal(); }
function showView(view) { document.querySelectorAll('.view').forEach(el => el.classList.toggle('active-view', el.id === `view-${view}`)); document.querySelectorAll('.nav-link').forEach(el => el.classList.toggle('active', el.dataset.view === view)); window.location.hash = view; }

document.querySelectorAll('[data-view]').forEach(link => link.addEventListener('click', event => { event.preventDefault(); showView(link.dataset.view); }));
document.getElementById('quick-add').addEventListener('click', () => openDialog('grade-dialog')); document.getElementById('grades-add').addEventListener('click', () => openDialog('grade-dialog')); document.getElementById('tip-add').addEventListener('click', () => openDialog('grade-dialog')); document.getElementById('subject-add').addEventListener('click', () => document.getElementById('subject-dialog').showModal()); document.getElementById('profile-button').addEventListener('click', () => { const p = data.profile; document.getElementById('profile-name').value = p.name; document.getElementById('profile-course').value = p.course; document.getElementById('profile-id').value = p.studentId; document.getElementById('profile-dialog').showModal(); });
document.getElementById('undo-button').addEventListener('click', undo); document.getElementById('redo-button').addEventListener('click', redo); document.getElementById('grade-search').addEventListener('input', renderGrades); document.getElementById('grade-filter').addEventListener('change', renderGrades);
document.getElementById('auth-switch').addEventListener('click', () => setAuthMode(document.getElementById('auth-form').dataset.mode !== 'register'));
document.getElementById('auth-form').addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.target); const username = form.get('username').trim().toLowerCase(); const password = form.get('password'); const accountUsers = users(); showAuthError(''); if (event.target.dataset.mode === 'register') { if (!form.get('fullName').trim() || !form.get('course').trim() || !form.get('studentId').trim()) return showAuthError('Please complete all profile fields.'); if (username.length < 3) return showAuthError('Username must be at least 3 characters.'); if (password.length < 6) return showAuthError('Password must be at least 6 characters.'); if (accountUsers[username]) return showAuthError('That username is already registered.'); accountUsers[username] = { password: await passwordHash(password), profile: { name: form.get('fullName').trim(), course: form.get('course').trim(), studentId: form.get('studentId').trim() } }; localStorage.setItem(USERS_KEY, JSON.stringify(accountUsers)); STORAGE_KEY = `gradetrack-data-${username}`; data = { ...structuredClone(defaultData), profile: accountUsers[username].profile }; saveData(); localStorage.setItem('gradetrack-session', username); setUser(username); toast('Account created'); } else { const account = accountUsers[username]; if (!account || account.password !== await passwordHash(password)) return showAuthError('Invalid username or password.'); if (form.get('remember')) localStorage.setItem('gradetrack-session', username); else sessionStorage.setItem('gradetrack-session', username); setUser(username); toast('Welcome back'); } });
document.getElementById('logout-button').addEventListener('click', () => { localStorage.removeItem('gradetrack-session'); sessionStorage.removeItem('gradetrack-session'); currentUser = null; document.querySelector('.app-shell').classList.add('hidden'); document.getElementById('auth-screen').classList.remove('hidden'); document.getElementById('auth-form').reset(); setAuthMode(false); });
document.getElementById('grade-form').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.target); const grade = { id: crypto.randomUUID(), subject: form.get('subject'), activity: form.get('activity').trim(), category: form.get('category'), score: Number(form.get('score')), total: Number(form.get('total')), date: form.get('date') }; if (grade.score > grade.total) return toast('Score cannot be higher than the total'); commit(`Added ${grade.activity}`, () => data.grades.push(grade)); event.target.reset(); document.getElementById('grade-dialog').close(); });
document.getElementById('subject-form').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.target); const name = form.get('name').trim(); if (data.subjects.some(s => s.name.toLowerCase() === name.toLowerCase())) return toast('That subject already exists'); commit(`Added ${name}`, () => data.subjects.push({ id: crypto.randomUUID(), name, weights: form.get('weights').trim() })); event.target.reset(); document.getElementById('subject-dialog').close(); });
document.getElementById('profile-form').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.target); commit('Updated profile', () => { data.profile = { name: form.get('name').trim(), course: form.get('course').trim(), studentId: form.get('studentId').trim() }; }); document.getElementById('profile-dialog').close(); });
document.getElementById('file-add').addEventListener('click', () => document.getElementById('file-input').click()); document.getElementById('file-input').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.addEventListener('load', () => { const subject = data.subjects[0]?.name || 'General'; commit(`Added ${file.name}`, () => data.files.push({ id: crypto.randomUUID(), name: file.name, subject, date: new Date().toISOString().slice(0, 10), content: reader.result })); event.target.value = ''; }); reader.addEventListener('error', () => { event.target.value = ''; toast('Unable to read this file'); }); reader.readAsDataURL(file); });
window.addEventListener('hashchange', () => { const view = location.hash.slice(1); if (['dashboard', 'grades', 'subjects', 'insights', 'files'].includes(view)) showView(view); });
const initialView = location.hash.slice(1); if (['dashboard', 'grades', 'subjects', 'insights', 'files'].includes(initialView)) showView(initialView); document.querySelector('.app-shell').classList.add('hidden'); setAuthMode(false); const rememberedUser = localStorage.getItem('gradetrack-session') || sessionStorage.getItem('gradetrack-session'); if (rememberedUser && users()[rememberedUser]) setUser(rememberedUser); else document.getElementById('auth-screen').classList.remove('hidden');
